In [13]:
import torch

torch.FloatTensor
True
tensor([[-1.3916,  0.4832,  1.0558],
        [-0.7756,  1.0993, -0.3350]])


In [6]:
# 标量1
a = torch.tensor(1.2)
a.shape
len(a.shape)
a.size()

torch.Size([])

In [9]:
# 标量的shape = 0， 没有维度
# 张量的有维度
# dim = 1
a = torch.tensor([1.1])
b = torch.tensor([1.1, 1.2])
c = torch.FloatTensor(1)
d = torch.FloatTensor(2)
import numpy as np
data = np.ones(2)
tensor_data = torch.from_numpy(data)
# torch.tensor 接受具体的数据
# torch.FloatTensor 接受指定的维度，随机生成数据

# 这种 dim=1 的张量一般用于表示 bias

In [12]:
a = torch.ones(2)
print(a.shape)
print(a.size())
print(a)


torch.Size([2])
torch.Size([2])
tensor([1., 1.])


In [14]:
# dim = 2
# 2*3 张量
a = torch.randn(2,3)
print(a.type())
print(isinstance(a, torch.FloatTensor))
print(a)
print(a.size(0))
print(a.size(1))
print(a.shape[1])

torch.FloatTensor
True
tensor([[ 1.2848, -0.7604, -0.2026],
        [ 0.7372,  2.0000, -0.9836]])
2
3
3


In [15]:
# dim = 3  3维张量
# 三维张量一般用于  RNN  input batch:  
# 一句话10个单词，每个单词编码为100维向量，10*100.   每次送入20句话  20*10*100
a =  torch.randn(1,2,3)
print(a.shape)
print(a)

torch.Size([1, 2, 3])
tensor([[[ 1.7942,  0.0869, -1.0131],
         [ 0.1038, -0.5450,  0.7466]]])


In [16]:
# dim = 4 4维张量，适用于图片类型 CNN (b, c, h, w)  batch, 通道数，长和宽
a = torch.rand(2,3,28,28)
print (a.shape)


torch.Size([2, 3, 28, 28])


In [ ]:
# 创建 tensor
